services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    build: spark/
    networks:
      iceberg_net:
    depends_on:
      - embucket
      - minio
    volumes:
      - warehouse_data:/home/iceberg/warehouse
      - notebooks_data:/home/iceberg/notebooks/notebooks
      - spark_events:/home/iceberg/spark-events
      - ./scripts/create_iceberg.py:/home/iceberg/create_iceberg.py
      - ./scripts/create_iceberg_partitioned.py:/home/iceberg/create_iceberg_partitioned.py
      - ./clickbench/partitioned:/home/iceberg/partitioned
      - ./clickbench/single:/home/iceberg/single
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=us-east-2
      - SPARK_DRIVER_MEMORY=16g
      - SPARK_EXECUTOR_MEMORY=16g
    ports:
      - 8888:8888
      # - 8080:8080
      # - 10000:10000
      # - 10001:10001
    entrypoint: /bin/sh
    command: >
      -c "
      echo \"
        spark.sql.extensions                   org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions \\n
        spark.sql.catalog.demo                 org.apache.iceberg.spark.SparkCatalog \\n
        spark.sql.catalog.demo.catalog-impl    org.apache.iceberg.rest.RESTCatalog \\n
        spark.sql.catalog.demo.uri             http://embucket:3000/catalog \\n
        spark.sql.catalog.demo.io-impl         org.apache.iceberg.aws.s3.S3FileIO \\n
        spark.sql.catalog.demo.warehouse       demo \\n
        spark.sql.catalog.demo.cache-enabled   false \\n
        spark.sql.catalog.demo.rest.access-key-id  AKIAIOSFODNN7EXAMPLE \\n
        spark.sql.catalog.demo.rest.secret-access-key wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \\n
        spark.sql.catalog.demo.rest.signing-region us-east-2 \\n
        spark.sql.catalog.demo.rest.sigv4-enabled  true \\n
        spark.sql.catalog.demo.s3.endpoint     http://warehouse.minio:9000 \\n
        spark.sql.defaultCatalog               demo \\n
        spark.eventLog.enabled                 true \\n 
        spark.eventLog.dir                     /home/iceberg/spark-events \\n
        spark.history.fs.logDirectory          /home/iceberg/spark-events \\n
        spark.sql.catalog.demo.s3.path-style-access  true \\n
      \" > /opt/spark/conf/spark-defaults.conf && ./entrypoint.sh notebook
      "
  embucket:
    image: embucket/embucket
    container_name: embucket
    depends_on:
      mc:
        condition: service_healthy
    networks:
      iceberg_net:
    ports:
      - 3000:3000
      - 8080:8080
    environment:
      - OBJECT_STORE_BACKEND=s3
      - SLATEDB_PREFIX=data/
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=us-east-2
      - S3_BUCKET=mybucket
      - S3_ENDPOINT=http://warehouse.minio:9000
      - S3_ALLOW_HTTP=true
      - CATALOG_URL=http://embucket:3000/catalog
      - RUST_LOG=info
    volumes:
      - tmp_data:/tmp
      - ./clickbench/partitioned:/storage/clickbench/partitioned
      - ./clickbench/single:/storage/clickbench/single
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    volumes:
      - warehouse_data:/warehouse
    networks:
      iceberg_net:
        aliases:
          - warehouse.minio
    ports:
      - 9001:9001
      - 9000:9000
    command: ['server', '/warehouse', '--console-address', ':9001']
  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      iceberg_net:
    environment:
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
      - AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      - AWS_REGION=us-east-2
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://warehouse.minio:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/mybucket;
      /usr/bin/mc mb minio/mybucket;
      /usr/bin/mc anonymous set public minio/mybucket;
      tail -f /dev/null
      "
    healthcheck:
      test: ['CMD', '/usr/bin/mc', 'ls', 'minio/mybucket']
      interval: 10s
      timeout: 5s
      retries: 3
volumes:
  warehouse_data:
  notebooks_data:
  spark_events:
  tmp_data:

networks:
  iceberg_net:
